In [1]:
import pandas as pd 
df = pd.read_csv("reviews.csv")
df.head()

reviewerID        asin         reviewerName  overall  unixReviewTime  \
0  A32T2H8150OJLU  B00000JBLH                  ARH      5.0      1094169600   
1  A3MAFS04ZABRGO  B00000JBLH     Let it Be "Alan"      5.0      1197676800   
2  A1F1A0QQP2XVH5  B00000JBLH               Mark B      2.0      1293840000   
3   A49R5DBXXQDE5  B00000JBLH         R. D Johnson      5.0      1145404800   
4  A2XRMQA6PJ5ZJ8  B00000JBLH  Roger J. Buffington      5.0      1375574400   

    reviewTime  helpful  total  \
0   09 3, 2004        3      4   
1  12 15, 2007        7      9   
2   01 1, 2011        3      3   
3  04 19, 2006        7      8   
4   08 4, 2013        0      0   

                                              review sentiment  
0  bought first hp c served faithfully lost trave...  positive  
1  belated review feel obliged share view old wor...  positive  
2  hp gx kicking twenty year hp year old still fl...  negative  
3  started finance stuff recently went looking go...  positive  
4  simple calculation discounted cash flow one st...  positive

In [2]:
print(df.columns)
print(df.shape)

Index(['reviewerID', 'asin', 'reviewerName', 'overall', 'unixReviewTime',
       'reviewTime', 'helpful', 'total', 'review', 'sentiment'],
      dtype='object')
(53258, 10)


In [3]:
count = df.groupby("asin", as_index=False).count()

In [4]:
dfMerged = pd.merge(df, count, how='right', on=['asin'])
dfMerged.head()

reviewerID_x        asin       reviewerName_x  overall_x  \
0  A32T2H8150OJLU  B00000JBLH                  ARH        5.0   
1  A3MAFS04ZABRGO  B00000JBLH     Let it Be "Alan"        5.0   
2  A1F1A0QQP2XVH5  B00000JBLH               Mark B        2.0   
3   A49R5DBXXQDE5  B00000JBLH         R. D Johnson        5.0   
4  A2XRMQA6PJ5ZJ8  B00000JBLH  Roger J. Buffington        5.0   

   unixReviewTime_x reviewTime_x  helpful_x  total_x  \
0        1094169600   09 3, 2004          3        4   
1        1197676800  12 15, 2007          7        9   
2        1293840000   01 1, 2011          3        3   
3        1145404800  04 19, 2006          7        8   
4        1375574400   08 4, 2013          0        0   

                                            review_x sentiment_x  \
0  bought first hp c served faithfully lost trave...    positive   
1  belated review feel obliged share view old wor...    positive   
2  hp gx kicking twenty year hp year old still fl...    negative   
3  started finance stuff recently went looking go...    positive   
4  simple calculation discounted cash flow one st...    positive   

   reviewerID_y  reviewerName_y  overall_y  unixReviewTime_y  reviewTime_y  \
0             8               8          8                 8             8   
1             8               8          8                 8             8   
2             8               8          8                 8             8   
3             8               8          8                 8             8   
4             8               8          8                 8             8   

   helpful_y  total_y  review_y  sentiment_y  
0          8        8         8            8  
1          8        8         8            8  
2          8        8         8            8  
3          8        8         8            8  
4          8        8         8            8

In [5]:
dfMerged["totalReviewers"] = dfMerged["reviewerID_y"]
dfMerged["overallScore"] = dfMerged["overall_x"]
dfMerged["review"] = dfMerged["review_x"]

dfCount = dfMerged[['asin','review','overallScore','totalReviewers']]

In [6]:
dfMerged = dfMerged.sort_values(by = "totalReviewers", ascending=False)
dfCount = dfMerged[dfMerged.totalReviewers >= 50]
dfCount

reviewerID_x        asin  \
13657  A1YVO5V1SO18DZ  B0010T3QT2   
13585  A1Z7Y2GMAP9SRY  B0010T3QT2   
13561   ADEZOPMPKK146  B0010T3QT2   
13560   AXNJFYJRDK7CJ  B0010T3QT2   
13559   AMYTL79JMGQ6D  B0010T3QT2   
...               ...         ...   
9537   A2QWEEYO8QLIMI  B000GP5L3U   
9538   A28YBL28P03P8V  B000GP5L3U   
9539   A36PFPY4O3E1DV  B000GP5L3U   
9540    AKDKA28LFN20O  B000GP5L3U   
9541   A3LDLV1GWQJLEQ  B000GP5L3U   

                                         reviewerName_x  overall_x  \
13657                                  The Bee Bee "BB"        4.0   
13585                          M. Thompson "Dyson Diva"        5.0   
13561                                              Meli        4.0   
13560  Megan Bostic "I like the sun, monkeys and I w...        5.0   
13559                                          Mary Ann        5.0   
...                                                 ...        ...   
9537                B. Rackley "Sierras Creative World"        5.0   
9538                                     Bradley Nelson        5.0   
9539                                       C. Fernandes        5.0   
9540                       Cowgirl Model "cowgirlmodel"        4.0   
9541                       eric talerico "Greenmanwest"        5.0   

       unixReviewTime_x reviewTime_x  helpful_x  total_x  \
13657        1277251200  06 23, 2010          0        0   
13585        1317686400   10 4, 2011          0        0   
13561        1279152000  07 15, 2010          0        0   
13560        1279670400  07 21, 2010          0        0   
13559        1277164800  06 22, 2010          1        2   
...                 ...          ...        ...      ...   
9537         1374624000  07 24, 2013          0        0   
9538         1378425600   09 6, 2013          0        0   
9539         1375574400   08 4, 2013          0        0   
9540         1255305600  10 12, 2009         27       27   
9541         1376956800  08 20, 2013          1        1   

                                                review_x sentiment_x  ...  \
13657  face quality park reveal n seal envelope stand...    positive  ...   
13585  rarely mail anything anymore like lick envelop...    positive  ...   
13561  like park reveal n seal envelope say like fact...    positive  ...   
13560  envelope thick opaque see enclosed check folde...    positive  ...   
13559  standard sized business letter envelope flip c...    positive  ...   
...                                                  ...         ...  ...   
9537   several year ago hubby purchased trimmer adver...    positive  ...   
9538   really much different similar product good siz...    positive  ...   
9539   much paper trimmer one westcott extra make nic...    positive  ...   
9540   wanted give trimmer star easily best trimmer e...    positive  ...   
9541   little trimmer sharp precise easy use blade ve...    positive  ...   

       overall_y  unixReviewTime_y  reviewTime_y  helpful_y  total_y  \
13657        311               311           311        311      311   
13585        311               311           311        311      311   
13561        311               311           311        311      311   
13560        311               311           311        311      311   
13559        311               311           311        311      311   
...          ...               ...           ...        ...      ...   
9537          50                50            50         50       50   
9538          50                50            50         50       50   
9539          50                50            50         50       50   
9540          50                50            50         50       50   
9541          50                50            50         50       50   

       review_y  sentiment_y  totalReviewers  overallScore  \
13657       311          311             311           4.0   
13585       311          311             311           5.0   
13561       311          3

#### Grouping all the summary Reviews by product ID

In [7]:
dfProductReview = df.groupby("asin", as_index=False).mean()
ProductReviewSummary = dfCount.groupby("asin")["review"].apply(list)
ProductReviewSummary = pd.DataFrame(ProductReviewSummary)
dfProductReview

asin   overall  unixReviewTime   helpful     total
0     B00000JBLH  4.625000    1.208974e+09  4.125000  5.000000
1     B00000JBLU  4.888889    1.289894e+09  3.000000  3.444444
2     B00000JBNX  4.391304    1.333618e+09  3.478261  3.913043
3     B00000JBO8  4.100000    1.314645e+09  3.100000  5.300000
4     B00000JFNV  4.727273    1.301755e+09  0.750000  0.840909
...          ...       ...             ...       ...       ...
2415  B00K5UZP2S  4.714286    1.404592e+09  3.142857  3.285714
2416  B00KLLBEPI  4.600000    1.405382e+09  2.200000  3.600000
2417  B00KOO594O  4.400000    1.404265e+09  0.200000  0.266667
2418  B00KOO599O  4.466667    1.404858e+09  0.333333  0.866667
2419  B00KYA0RC2  4.750000    1.405134e+09  1.250000  1.375000

[2420 rows x 5 columns]

In [8]:
df3 = ProductReviewSummary
df3 = pd.merge(df3, dfProductReview, on="asin", how='inner')
df3 = df3[['asin','review','overall']]
df3

asin                                             review   overall
0    B00004Z498  [received product vine program couple exit sig...  4.712121
1    B00004Z5QO  [usually love avery product must say adding pr...  4.718310
2    B00004Z5SM  [experimented number different brand label alw...  4.807692
3    B00004Z5SN  [overall good label complaint really count sin...  4.517857
4    B00004Z69W  [every try store brand usually fine still biz ...  4.726027
..          ...                                                ...       ...
286  B00G411O8G  [received pack swingline thermal laminating le...  4.503817
287  B00GLZZSN2  [today review arrow pt pneumatic staple gun jo...  4.620000
288  B00GMOOAIQ  [good quality sturdy little box like much easy...  4.520000
289  B00GO4GNPC  [kudos swingline coming innovative idea small ...  3.794118
290  B00JAKXFQW  [textured wraparound label good specialty use ...  4.586207

[291 rows x 3 columns]

In [9]:
df3['review'] = df3["review"].astype(str)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from pandas import DataFrame 

countVector = CountVectorizer() 

transformedReviews = countVector.fit_transform(df3["review"]) 

dfReviews = DataFrame(transformedReviews.A, columns=countVector.get_feature_names())

### KNN to find similar products

In [11]:
from sklearn.neighbors import NearestNeighbors
from sklearn import neighbors
import numpy as np

X = np.array(dfReviews)
 # create train and test
tpercent = 0.90
tsize = int(np.floor(tpercent * len(dfReviews)))
dfReviews_train = X[:tsize]
dfReviews_test = X[tsize:]
#len of train and test
lentrain = len(dfReviews_train)
lentest = len(dfReviews_test)

In [12]:
neighbor = NearestNeighbors(n_neighbors=3,algorithm='ball_tree').fit(dfReviews_train) 

In [16]:
for i in range(lentest):
    a = neighbor.kneighbors([dfReviews_test[i]])
    print(a)
    related_product_list = a[1]

    first_related_product = [item[0] for item in related_product_list]
    first_related_product = str(first_related_product).strip('[]')
    first_related_product = int(first_related_product)
    second_related_product = [item[1] for item in related_product_list]
    second_related_product = str(second_related_product).strip('[]')
    second_related_product = int(second_related_product)
    third_related_product = [item[2] for item in related_product_list]
    third_related_product = str(third_related_product).strip('[]')
    third_related_product = int(third_related_product)
    
    print ("Based on product reviews, for ", df3["asin"][lentrain + i]," average rating is ",df3["overall"][lentrain + i])
    print ("1 : ", df3["asin"][first_related_product])
    print ("2 :", df3["asin"][second_related_product])
    print ("3 :", df3["asin"][third_related_product])

    print ("-")

(array([[169.3339895 , 281.2312216 , 364.16479786]]), array([[173, 217, 249]], dtype=int64))
Based on product reviews, for  B00CRGP8B6  average rating is  4.203125
1 :  B004GEC2L6
2 : B007TRUWG4
3 : B00BMLQSNO
-
(array([[125.28766899, 154.65122049, 200.29727906]]), array([[256, 257, 176]], dtype=int64))
Based on product reviews, for  B00CWY2KFU  average rating is  4.428571428571429
1 :  B00COHAJXA
2 : B00COHALXI
3 : B004HY9IJE
-
(array([[276.45252757, 322.96903876, 362.49827586]]), array([[218, 222, 220]], dtype=int64))
Based on product reviews, for  B00CWZHA6S  average rating is  4.151515151515151
1 :  B007XPBW1G
2 : B0085IQ28I
3 : B0085IPYO6
-
(array([[211.896201  , 227.95174928, 228.59352572]]), array([[201,  34,  27]], dtype=int64))
Based on product reviews, for  B00D3EWHU6  average rating is  4.140845070422535
1 :  B00548SAP0
2 : B0006HX1HG
3 : B000087KUA
-
(array([[239.03137869, 246.19707553, 246.97773179]]), array([[175,  52, 112]], dtype=int64))
Based on product reviews, for  B

In [14]:
neighbor

NearestNeighbors(algorithm='ball_tree', n_neighbors=3)